apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredump-hostpath-pv
spec:
  capacity:
    storage: 10Gi # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard # Or your specific storage class
  hostPath:
    path: "/var/crashdumps"
