apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dotnet-memory-leak-route-host-coredump
  namespace: dotnet-memory-leak-app
spec:
  port:
    targetPort: 8881
  to:
    kind: Service
    name: dotnet-memory-leak-service-host-coredump
